### ISSUE TITLE
高难钓鱼反馈

### ISSUE THREAD

**Issue by shunin0424** [EBSMMF/FFXIV_Tools#1]
反馈，无风钓场的高难钓鱼会专一白影和皇家披风，不知道是不是设置问题

**Comment by lothar007** [comment]
好家伙我直接不会自动提钩，然后无差别专一

**Comment by shunin0424** [comment]
我这轻杆不管，中杆专一

**Comment by lothar007** [comment]
你有专门把触发器里的端口改成和鲶鱼精监听的一样吗？我直接用没反应，都手动改成2019了，可是还是有问题

**Comment by shunin0424** [comment]
不用，鲶鱼精应该是执行了的

**Comment by EBSMMF** [comment]
> 好家伙我直接不会自动提钩，然后无差别专一
哪个时候抹茶是没更新的，，现在更新了，我在改

**Comment by EBSMMF** [comment]
> 好家伙我直接不会自动提钩，然后无差别专一

已经更新了国服5.31鱼名字的适配和抹茶提供的钓鱼信息适配

**Comment by EBSMMF** [comment]
> 你有专门把触发器里的端口改成和鲶鱼精监听的一样吗？我直接用没反应，都手动改成2019了，可是还是有问题

端口号改成了默认2019，并推送了XD

**Comment by shunin0424** [comment]
[emmmm还是有点问题，抛杆动作无法触发，应该是要把触发选项里的忽略父组分组限制勾上，然后就是拍水后平钓会把DH重新禁用，钓蝠宝的那一下会重新变成普通提竿。然后给的建议就是可以设置等一下强心剂和gp恢复？[https://img.nga.178.com/attachments/mon_202101/06/-7s28Q5-gf97ZcT3cSvr-fu.png](url)

**Comment by EBSMMF** [comment]
> [emmmm还是有点问题，抛杆动作无法触发，应该是要把触发选项里的忽略父组分组限制勾上，然后就是拍水后平钓会把DH重新禁用，钓蝠宝的那一下会重新变成普通提竿。然后给的建议就是可以设置等一下强心剂和gp恢复？
> ![image](https://user-images.githubusercontent.com/19189612/103850775-1d0b2500-50e3-11eb-8d6e-4eb5f2b294a6.png)

猫猫ka粘土,猫猫放弃思考,关于无法抛竿的问题,你试试把5.31钓鱼高难的触发器里面的蒂蒂安设置删掉,拍水后平钓禁用DH不是很清楚原因,,DH是新设置的部分应该不会被其他的取消,很迷,

**Comment by shunin0424** [comment]
哈哈哈哈有空试试，麻烦了

**Comment by shunin0424** [comment]
草，试了一下发现双提后没接专一（

**Comment by shunin0424** [comment]
仔细看了下专一的gp最低值变成了650，但是刚双提后gp好像到不了650

**Comment by EBSMMF** [comment]
> 仔细看了下专一的gp最低值变成了650，但是刚双提后gp好像到不了650

唔，双提最低还是设置的350的，，在专一/拍水下上钩分类，第一条

**Comment by shunin0424** [comment]
我本地改了（）

**Comment by EBSMMF** [comment]
> 我本地改了（）

挠头

**Comment by shunin0424** [comment]
挠头

**Comment by shunin0424** [comment]
> > 我本地改了（）
> 
> 挠头

挠头
